### PR TITLE
Increase unit test coverage

### PR DESCRIPTION
**Pull request by itayox**
image

### CODE REVIEW

**Review by nvuillam — DISMISSED** [review]
Nice :)

**Comment by nvuillam** [comment]
@itayox there is a failing test in Build CI job :/

**Review by nvuillam — CHANGES_REQUESTED** [review]
Please can you make the build CI job work ? ( there is a failing test case)

**Comment by itayox** [comment]
Fixing it 👍

**Comment by itayox** [comment]
@nvuillam Fixed :)

**Pull request merged**
